M48
; DRILL file {KiCad 8.0.1} date 2025-04-04T11:24:13-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-04T11:24:13-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X155.605Y-131.11
X155.605Y-136.89
T2
X194.5Y-121.0
T3
X153.5Y-117.5
X153.5Y-150.5
X194.5Y-150.5
M30
