M48
; DRILL file {KiCad 8.0.1} date 2024-10-08T21:23:56-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-08T21:23:56-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X155.605Y-131.11
X155.605Y-136.89
T2
X170.9Y-150.2
X187.2Y-133.8
M30
